"""'User增加新的字段'

Revision ID: 53560b20d7e0
Revises: 62c3c3e0676b
Create Date: 2019-09-30 03:34:56.352525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53560b20d7e0'
down_revision = '62c3c3e0676b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
